server:
  port: 80

spring:
  application:
    name: consumer-order-service
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver   #SQL驱动包
    url: jdbc:mysql://localhost:3306/cloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
#      单机版
#      defaultZone: http://localhost:7001/eureka/
#    集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

    #是否加入注册中心
    register-with-eureka: true
    #是否从注册中心抓取已有注册信息，默认为true，单节点无所谓 ，集群必须设置为true才能配合ribbon使用负载
    fetch-registry: true
#    eureka可视化页面显示服务名称
  instance:
    instance-id: order80
#    eureka 是否显示IP地址
    prefer-ip-address: true
#    Eureka客户端向服务的发送心跳的间隔 默认30秒
    lease-renewal-interval-in-seconds: 2
#    Eureka客户端在最后一次收到心跳后等待的时间上限，默认90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2